version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Cargo Workspace
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain Dockerfile at root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Dockerfile at backend/
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Keycloak docker-compose at backend/keycloak/
  - package-ecosystem: "docker"
    directory: "/backend/keycloak"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Android dependencies
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain Tauri GUI / Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/gui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
