use anyhow::{Context, Result};
use std::net::{Ipv4Addr, Ipv6Addr};
use std::process::Command;
use tracing::{info, warn};

use super::command::run_cmd;

/// Configures DNS to use the VPN's DNS servers.
/// Returns the backup of the previous resolv.conf (if applicable) and whether resolvconf was used.
pub(super) fn configure_dns(
    tun_name: &str,
    dns_v4: Ipv4Addr,
    dns_v6: Option<Ipv6Addr>,
) -> Result<(Option<Vec<u8>>, bool)> {
    // Strategy 1: Try systemd-resolved via resolvectl
    if is_systemd_resolved_active() {
        info!("Using systemd-resolved for DNS configuration");

        let dns_v4_s = dns_v4.to_string();
        let dns_v6_s = dns_v6.map(|v6| v6.to_string());
        let mut dns_args: Vec<&str> = vec!["dns", tun_name, &dns_v4_s];
        if let Some(ref v6) = dns_v6_s {
            dns_args.push(v6);
        }

        let _ = run_cmd("resolvectl", &dns_args);
        let _ = run_cmd("resolvectl", &["domain", tun_name, "~."]);
        // Set the VPN interface as default route for DNS
        let _ = run_cmd("resolvectl", &["default-route", tun_name, "true"]);

        return Ok((None, true));
    }

    // Strategy 2: Direct /etc/resolv.conf modification
    info!("Using /etc/resolv.conf for DNS configuration");

    // Only back up the file if it does NOT already carry the Mavi marker.
    // Otherwise a previous session that was killed before cleanup (crash,
    // SIGKILL, power loss) would have left its own nameserver line in place,
    // and capturing that as the "original" would mean `restore_dns` later
    // writes the VPN's own DNS back — permanently pointing the host at a
    // nameserver that is only reachable while the (now-gone) tunnel is up.
    //
    // On the first successful overwrite we also mirror the original bytes to
    // a durable on-disk backup (`/var/lib/mavi-vpn/resolv.conf.backup`), so a
    // crash between `apply` and `cleanup` doesn't strand the host with a dead
    // nameserver: the next session (or even a manual restore) can recover the
    // real resolv.conf even though the in-memory backup is gone.
    let current = std::fs::read(RESOLV_CONF_PATH).ok();
    let backup = match current {
        Some(bytes) if is_mavi_generated_resolv_conf(&bytes) => {
            // A previous session already overwrote /etc/resolv.conf and died
            // before it could restore. Fall back to the persistent backup we
            // saved at that time.
            match load_persistent_backup() {
                Some(persisted) => {
                    info!(
                        "Recovered original /etc/resolv.conf from persistent backup at {} \
                         (previous session appears to have crashed)",
                        BACKUP_PATH
                    );
                    Some(persisted)
                }
                None => {
                    warn!(
                        "/etc/resolv.conf was left over from a previous Mavi VPN session \
                         and no persistent backup at {} is available. On stop we will \
                         fall back to public resolvers to keep DNS working.",
                        BACKUP_PATH
                    );
                    None
                }
            }
        }
        Some(bytes) => {
            if let Err(e) = save_persistent_backup(&bytes) {
                warn!(
                    "Failed to write persistent resolv.conf backup to {}: {}. \
                     A crash before stop may leave DNS pointing at the VPN resolver.",
                    BACKUP_PATH, e
                );
            }
            Some(bytes)
        }
        None => None,
    };

    let mut content = format!(
        "# Generated by Mavi VPN - DO NOT EDIT\nnameserver {}\n",
        dns_v4
    );
    if let Some(v6) = dns_v6 {
        content.push_str(&format!("nameserver {}\n", v6));
    }

    std::fs::write(RESOLV_CONF_PATH, &content)
        .context("Failed to write /etc/resolv.conf. Are you running as root?")?;

    Ok((backup, false))
}

/// Restores DNS configuration to its pre-VPN state.
///
/// Preference order:
///   1. In-memory backup captured at `configure_dns` time.
///   2. Persistent on-disk backup at `BACKUP_PATH`, used to survive crashes
///      between `apply` and `cleanup`.
///   3. Safe fallback nameservers (public resolvers) so the host keeps
///      working DNS instead of being left pointing at a dead VPN resolver.
pub(super) fn restore_dns(backup: &Option<Vec<u8>>, used_resolvconf: bool) {
    if used_resolvconf {
        // systemd-resolved cleans up automatically when the interface goes down
        info!("systemd-resolved will restore DNS automatically");
        return;
    }

    let restored = if let Some(ref data) = backup {
        write_resolv_conf(data, "in-memory backup")
    } else if let Some(persisted) = load_persistent_backup() {
        write_resolv_conf(&persisted, "persistent backup")
    } else {
        warn!(
            "No resolv.conf backup available (neither in-memory nor at {}). \
             Writing safe fallback nameservers so DNS keeps working.",
            BACKUP_PATH
        );
        write_resolv_conf(FALLBACK_RESOLV_CONF.as_bytes(), "fallback resolvers")
    };

    if restored {
        clear_persistent_backup();
    }
}

fn write_resolv_conf(data: &[u8], source_label: &str) -> bool {
    match std::fs::write(RESOLV_CONF_PATH, data) {
        Ok(()) => {
            info!("Restored /etc/resolv.conf from {}", source_label);
            true
        }
        Err(e) => {
            warn!(
                "Failed to restore /etc/resolv.conf from {}: {}",
                source_label, e
            );
            false
        }
    }
}

/// Writes the pre-VPN resolv.conf to a durable location that survives crashes.
/// Created with 0o600 via `O_CREAT | O_EXCL | O_NOFOLLOW` so the file can't be
/// pre-created as a symlink to somewhere else and so it isn't world-readable.
fn save_persistent_backup(bytes: &[u8]) -> std::io::Result<()> {
    use std::io::Write;
    use std::os::unix::fs::{DirBuilderExt, OpenOptionsExt};

    if let Some(parent) = std::path::Path::new(BACKUP_PATH).parent() {
        // Create the directory securely with 0o700 permissions from the start.
        // This ensures the backup (which mirrors /etc/resolv.conf, normally
        // world-readable but potentially containing search-domain hints) isn't
        // listable by non-root users at any point.
        std::fs::DirBuilder::new()
            .recursive(true)
            .mode(0o700)
            .create(parent)?;
    }

    // Best-effort unlink of any stale file (old mode, wrong owner, symlink).
    let _ = std::fs::remove_file(BACKUP_PATH);

    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .custom_flags(libc::O_NOFOLLOW)
        .open(BACKUP_PATH)?;
    f.write_all(bytes)?;
    f.sync_all()
}

pub(super) fn load_persistent_backup() -> Option<Vec<u8>> {
    match std::fs::read(BACKUP_PATH) {
        Ok(bytes) if !bytes.is_empty() => Some(bytes),
        Ok(_) => None,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            warn!(
                "Failed to read persistent resolv.conf backup at {}: {}",
                BACKUP_PATH, e
            );
            None
        }
    }
}

fn clear_persistent_backup() {
    match std::fs::remove_file(BACKUP_PATH) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => warn!(
            "Failed to remove persistent resolv.conf backup at {}: {}",
            BACKUP_PATH, e
        ),
    }
}

fn is_systemd_resolved_active() -> bool {
    Command::new("systemctl")
        .args(["is-active", "--quiet", "systemd-resolved"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Marker written at the top of `/etc/resolv.conf` while the VPN owns DNS.
/// Used to detect files left behind by a previous (crashed) session so we
/// don't adopt the VPN's own nameserver line as the "original" backup.
const RESOLV_CONF_MARKER: &[u8] = b"# Generated by Mavi VPN";

/// Path of the system resolver configuration we manage.
pub(super) const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";

/// Durable copy of the pre-VPN `/etc/resolv.conf`. Used to recover the
/// original DNS configuration after a crash between `apply` and `cleanup`,
/// and to seed `restore_dns` when the in-memory backup is missing because the
/// current process found a Mavi-marked file at startup.
const BACKUP_PATH: &str = "/var/lib/mavi-vpn/resolv.conf.backup";

/// Last-resort resolv.conf content when neither the in-memory nor the
/// persistent backup is available. Keeps name resolution working instead of
/// leaving the host pointing at the dead VPN resolver (e.g. 10.8.0.1).
const FALLBACK_RESOLV_CONF: &str = "\
# Restored by Mavi VPN - original resolv.conf was not available
nameserver 1.1.1.1
nameserver 9.9.9.9
";

pub(super) fn is_mavi_generated_resolv_conf(bytes: &[u8]) -> bool {
    bytes.starts_with(RESOLV_CONF_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_detected_on_mavi_generated_file() {
        let bytes = b"# Generated by Mavi VPN - DO NOT EDIT\nnameserver 10.8.0.1\n";
        assert!(is_mavi_generated_resolv_conf(bytes));
    }

    #[test]
    fn marker_absent_on_real_resolv_conf() {
        let bytes = b"# Provided by systemd-resolved\nnameserver 1.1.1.1\n";
        assert!(!is_mavi_generated_resolv_conf(bytes));
    }

    #[test]
    fn marker_requires_prefix_not_substring() {
        let bytes = b"nameserver 1.1.1.1\n# Generated by Mavi VPN\n";
        assert!(!is_mavi_generated_resolv_conf(bytes));
    }

    #[test]
    fn empty_file_is_not_marked() {
        assert!(!is_mavi_generated_resolv_conf(b""));
    }

    #[test]
    fn fallback_resolv_conf_is_parseable() {
        let mut nameservers = 0;
        for line in FALLBACK_RESOLV_CONF.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let rest = line
                .strip_prefix("nameserver ")
                .expect("fallback line must be a nameserver directive");
            rest.parse::<std::net::IpAddr>()
                .expect("fallback nameserver must be a valid IP");
            nameservers += 1;
        }
        assert!(
            nameservers >= 1,
            "fallback resolv.conf must list at least one nameserver"
        );
    }

    #[test]
    fn marker_detected_with_crlf_line_endings() {
        let bytes = b"# Generated by Mavi VPN - DO NOT EDIT\r\nnameserver 10.8.0.1\r\n";
        assert!(is_mavi_generated_resolv_conf(bytes));
    }

    #[test]
    fn fallback_has_two_nameservers() {
        let count = FALLBACK_RESOLV_CONF
            .lines()
            .filter(|l| l.trim().starts_with("nameserver "))
            .count();
        assert!(count >= 2);
    }

    #[test]
    fn marker_prefix_is_exact() {
        assert!(!is_mavi_generated_resolv_conf(
            b"# generated by mavi vpn - do not edit\n"
        ));
    }
}
